DROP TABLE IF EXISTS MESSAGESS;
/*CREATING THE RECIPIENTS TABLE*/
CREATE TABLE IF NOT EXISTS RECIPIENTS (
    recipient_id INTEGER PRIMARY KEY AUTOINCREMENT,
    firstname TEXT NOT NULL,
    lastname TEXT NOT NULL,
    email_address TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    carrier TEXT NOT NULL,
    enabled BOOLEAN,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

/*CREATING THE MESSAGES TABLE*/
CREATE TABLE IF NOT EXISTS MESSAGES (
    message_id INTEGER PRIMARY KEY AUTOINCREMENT,
    recipient_id TEXT NOT NULL,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    sent_at TEXT NOT NULL,
    direction TEXT NOT NULL,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (recipient_id) REFERENCES RECIPIENTS(recipient_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE   
);

/*CREATING THE LU_REMINDERS TABLE*/
CREATE TABLE IF NOT EXISTS LU_REMINDERS (
    reminder_id INTEGER PRIMARY KEY AUTOINCREMENT,
    category TEXT NOT NULL,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);